function SSPika() {
    this.fontfamily = "SSPika";
    this.charcode = {
        "notifications disabled": "🔕",
        "notification disabled": "🔕",
        "wheelchair accessible": "♿",
        notificationsdisabled: "🔕",
        notificationdisabled: "🔕",
        "horizontal bar chart": "",
        "downwards line chart": "📉",
        wheelchairaccessible: "♿",
        "line chart clipboard": "",
        "downwards bar chart": "",
        "medical thermometer": "",
        linechartclipboard: "",
        "upwards line chart": "📈",
        medicalthermometer: "",
        "telephone disabled": "",
        downwardslinechart: "📉",
        horizontalbarchart: "",
        "wine glass sparkle": "",
        "compact lightbulb": "",
        telephonedisabled: "",
        "navigation mobile": "",
        downwardsbarchart: "",
        "upwards bar chart": "",
        "charging battery": "",
        navigationmobile: "",
        compactlightbulb: "",
        "cooking utensils": "",
        "writing disabled": "",
        "pie chart thirds": "",
        "anatomical heart": "",
        wineglasssparkle: "",
        upwardslinechart: "📈",
        "compass navigate": "",
        "music open book": "",
        compassnavigate: "",
        "check clipboard": "",
        "pencil disabled": "",
        upwardsbarchart: "",
        writingdisabled: "",
        anatomicalheart: "",
        cookingutensils: "",
        chargingbattery: "",
        "delete calendar": "",
        "shopping basket": "",
        "download folder": "",
        "remove calendar": "",
        deletecalendar: "",
        "traffic camera": "",
        "baseball glove": "",
        "delivery truck": "",
        "bathroom scale": "",
        "steering wheel": "",
        downloadfolder: "",
        "weather online": "",
        "battery mobile": "",
        checkclipboard: "",
        "download cloud": "",
        pencildisabled: "",
        "christmas tree": "🎄",
        "search barcode": "",
        "phone disabled": "",
        "check calendar": "",
        piechartthirds: "",
        "medium battery": "",
        "wifi open book": "",
        "picture folder": "",
        "download crate": "",
        shoppingbasket: "",
        removecalendar: "",
        "globe location": "",
        "support ribbon": "🎀",
        "navigate right": "▻",
        announcements: "📢",
        picturefolder: "",
        "exercise bike": "",
        supportribbon: "🎀",
        "download file": "",
        weatheronline: "",
        baseballglove: "",
        globelocation: "",
        "compass arrow": "",
        "realty online": "",
        "browse online": "",
        "medical cross": "",
        trafficcamera: "",
        "navigate down": "",
        "traffic light": "🚦",
        deliverytruck: "",
        bathroomscale: "",
        "female avatar": "👧",
        steeringwheel: "",
        "scatter chart": "",
        "rubber eraser": "",
        "partly cloudy": "⛅",
        batterymobile: "",
        "settings file": "",
        downloadcloud: "",
        musicopenbook: "",
        "dollar mobile": "",
        "tropical fish": "",
        downloadcrate: "",
        "business user": "",
        "empty battery": "",
        christmastree: "🎄",
        "shopping cart": "",
        navigateright: "▻",
        phonedisabled: "",
        mediumbattery: "",
        notifications: "🔔",
        "download book": "",
        "call disabled": "",
        "previous page": "⎗",
        "download cart": "",
        "dispense cash": "",
        checkcalendar: "",
        "measuring cup": "",
        "bell disabled": "🔕",
        "navigate left": "◅",
        "upload folder": "",
        "secure folder": "",
        "cash register": "",
        searchbarcode: "",
        uploadfolder: "",
        trafficlight: "🚦",
        "digital safe": "",
        dispensecash: "",
        downloadcart: "",
        "partly sunny": "⛅",
        notification: "🔔",
        thunderstorm: "⛈",
        shoppingcart: "",
        "tape measure": "",
        businessuser: "",
        "user profile": "",
        partlycloudy: "⛅",
        scatterchart: "",
        femaleavatar: "👧",
        "delivery van": "",
        "this side up": "",
        tropicalfish: "",
        "search house": "",
        compassarrow: "",
        medicalcross: "",
        "map location": "",
        "add calendar": "",
        "train tunnel": "🚇",
        donotdisturb: "",
        "vinyl record": "",
        "movie folder": "",
        exercisebike: "",
        "fast forward": "⏩",
        announcement: "📢",
        securefolder: "",
        "skip forward": "⏭",
        "cloud folder": "",
        cashregister: "",
        belldisabled: "🔕",
        downloadbook: "",
        calldisabled: "",
        "rubber stamp": "",
        "paint roller": "",
        "table tennis": "",
        rubbereraser: "",
        navigatedown: "",
        "mobile phone": "",
        navigateleft: "◅",
        wifiopenbook: "",
        "picture file": "",
        "full battery": "🔋",
        "high battery": "",
        emptybattery: "",
        "heart mobile": "",
        "phone mobile": "",
        dollarmobile: "",
        "weather vane": "",
        "power mobile": "",
        browseonline: "",
        realtyonline: "",
        "direct right": "▹",
        "lightbulb on": "",
        "picnic table": "",
        settingsfile: "",
        previouspage: "⎗",
        "download box": "",
        measuringcup: "",
        "upload cloud": "",
        "upload crate": "",
        intersection: "",
        downloadfile: "",
        "rotate right": "↻",
        skipforward: "⏭",
        deliveryvan: "",
        "rotate left": "↺",
        "lock folder": "",
        tapemeasure: "",
        "female user": "👧",
        "broken bone": "",
        "credit card": "💳",
        "solar panel": "",
        stethoscope: "",
        "male avatar": "👤",
        rubberstamp: "",
        "search book": "",
        "eye surgery": "",
        searchhouse: "",
        tabletennis: "",
        paintroller: "",
        "open folder": "📂",
        "check heart": "",
        "alarm clock": "⏰",
        mobilephone: "",
        thermometer: "",
        "walky talky": "",
        "delete cart": "",
        digitalsafe: "",
        traintunnel: "🚇",
        fullbattery: "🔋",
        maplocation: "",
        highbattery: "",
        userprofile: "",
        "delete date": "",
        "empty heart": "♡",
        "low battery": "",
        addcalendar: "",
        "thumbs down": "👎",
        heartmobile: "",
        "delete user": "",
        phonemobile: "",
        "remove user": "",
        "lock mobile": "",
        "text mobile": "",
        "floppy disk": "💾",
        "euro mobile": "",
        information: "ℹ",
        weathervane: "",
        directright: "▹",
        powermobile: "",
        "eighth note": "♪",
        "remove cart": "",
        "shop online": "",
        "bank online": "",
        "high volume": "🔊",
        vinylrecord: "",
        "read online": "",
        lightbulbon: "",
        "line charts": "",
        picnictable: "",
        cloudfolder: "",
        picturefile: "",
        "direct down": "▾",
        waterbottle: "",
        "direct left": "◃",
        moviefolder: "",
        "export file": "",
        "import file": "",
        "upload file": "",
        photographs: "🌄",
        downloadbox: "",
        videocamera: "📹",
        temperature: "",
        uploadcloud: "",
        "navigate up": "",
        uploadcrate: "",
        fastforward: "⏩",
        partlysunny: "⛅",
        supplements: "",
        rotateright: "↻",
        "pill bottle": "",
        "delete file": "",
        "remove file": "",
        "remove date": "",
        deletedate: "",
        linecharts: "",
        motorcycle: "",
        alarmclock: "⏰",
        brokenbone: "",
        "pull quote": "“",
        "spoon fork": "",
        "floor plan": "",
        lowbattery: "",
        photograph: "🌄",
        "empty cart": "",
        emptyheart: "♡",
        "half heart": "",
        navigateup: "",
        "user group": "",
        "play video": "",
        removedate: "",
        deletecart: "",
        lockmobile: "",
        "house sale": "",
        textmobile: "",
        navigation: "",
        automobile: "🚘",
        thumbsdown: "👎",
        euromobile: "",
        directions: "",
        "rss mobile": "",
        disapprove: "👎",
        maleavatar: "👤",
        calculator: "",
        creditcard: "💳",
        rotateleft: "↺",
        removecart: "",
        "down right": "⬊",
        "flower tag": "",
        shoponline: "",
        lockfolder: "",
        bankonline: "",
        locomotive: "🚂",
        eyesurgery: "",
        deleteuser: "",
        readonline: "",
        checkheart: "",
        descending: "▾",
        "wine glass": "🍷",
        "heart book": "",
        femaleuser: "👧",
        directdown: "▾",
        "no smoking": "🚭",
        "hair dryer": "",
        "cargo ship": "",
        pillbottle: "",
        containers: "",
        searchbook: "",
        floppydisk: "💾",
        directleft: "◃",
        solarpanel: "",
        "left right": "⬌",
        "scale down": "",
        "hard drive": "",
        exportfile: "",
        thissideup: "",
        importfile: "",
        thumbnails: "",
        uploadfile: "",
        eighthnote: "♪",
        attachment: "📎",
        visibility: "👀",
        openfolder: "📂",
        removeuser: "",
        "bank check": "",
        binoculars: "",
        "grid lines": "",
        smartphone: "",
        "upload box": "",
        microphone: "🎤",
        departures: "",
        wheelchair: "♿",
        "check date": "",
        "cell phone": "📱",
        walkytalky: "",
        helicopter: "🚁",
        interstate: "",
        "low volume": "🔉",
        deletefile: "",
        eyedropper: "",
        connection: "",
        screenshot: "",
        highvolume: "🔊",
        removefile: "",
        paperclip: "📎",
        "palm tree": "🌴",
        evergreen: "🌲",
        piggybank: "",
        playvideo: "",
        gridlines: "",
        "direct up": "▴",
        "money bag": "💰",
        briefcase: "💼",
        warehouse: "",
        rssmobile: "",
        floorplan: "",
        checkdate: "",
        "skip back": "⏮",
        calculate: "",
        "next page": "⎘",
        "down left": "⬋",
        housesale: "",
        "thumbs up": "👍",
        "bear face": "🐻",
        "pie chart": "",
        backspace: "⌫",
        checkmark: "✓",
        badminton: "",
        "hot sauce": "",
        ambulance: "🚑",
        heartbook: "",
        "wifi mail": "",
        "bar chart": "📊",
        nosmoking: "🚭",
        lightbulb: "💡",
        billiards: "🎱",
        emptycart: "",
        leftright: "⬌",
        "ice skate": "⛸",
        downright: "⬊",
        hamburger: "🍔",
        hairdryer: "",
        ascending: "▴",
        newspaper: "📰",
        analytics: "",
        halfheart: "",
        "user file": "",
        crosshair: "⌖",
        "lock file": "",
        "olive oil": "",
        "male user": "👤",
        christmas: "🎄",
        rightward: "",
        "page curl": "",
        clockwise: "⥁",
        spoonfork: "",
        wineglass: "🍷",
        scaledown: "",
        "three die": "⚂",
        harddrive: "",
        telephone: "📞",
        "call bell": "",
        stopwatch: "⏱",
        cellphone: "📱",
        musicnote: "♫",
        sunscreen: "",
        usergroup: "",
        "egg timer": "",
        dashboard: "",
        "text file": "",
        "wifi book": "",
        "bbq apron": "",
        uploadbox: "",
        departure: "",
        "half star": "",
        "ice cream": "🍨",
        lowvolume: "🔉",
        spaghetti: "🍝",
        "price tag": "",
        snowflake: "❄",
        cargoship: "",
        highlight: "",
        flowertag: "",
        "open book": "📖",
        "side dish": "🍚",
        pullquote: "“",
        megaphone: "📢",
        "jump rope": "",
        bankcheck: "",
        palmtree: "🌴",
        "add file": "",
        "five die": "⚄",
        "four die": "⚃",
        threedie: "⚂",
        elevator: "",
        lockfile: "",
        userfile: "",
        campfire: "🔥",
        iceskate: "⛸",
        textfile: "",
        wifibook: "",
        passport: "",
        jerrycan: "",
        computer: "💻",
        pagecurl: "",
        notebook: "📓",
        openbook: "📖",
        document: "",
        football: "🏈",
        exercise: "",
        skipback: "⏮",
        dumbbell: "",
        jumprope: "",
        pictures: "🌄",
        "sky lift": "🚡",
        meditate: "",
        schooner: "",
        typeface: "",
        sailboat: "⛵",
        suitcase: "",
        redirect: "↪",
        contract: "",
        question: "❓",
        arrivals: "",
        callbell: "",
        "sign out": "",
        "scale up": "",
        database: "",
        firewall: "",
        hospital: "⛨",
        subtract: "-",
        location: "",
        signpost: "",
        bearface: "🐻",
        navigate: "",
        building: "🏢",
        download: "",
        seedling: "🌱",
        forklift: "",
        settings: "⚙",
        umbrella: "☂",
        barchart: "📊",
        piechart: "",
        moneybag: "💰",
        banknote: "💵",
        fracture: "",
        "add cart": "",
        "add user": "",
        "up right": "⬈",
        maleuser: "👤",
        calendar: "📅",
        wifimail: "",
        downleft: "⬋",
        "add date": "",
        envelope: "✉",
        facetime: "",
        "end call": "",
        bullseye: "🎯",
        halfstar: "",
        favorite: "⋆",
        previous: "◅",
        directup: "▴",
        thumbsup: "👍",
        sidedish: "🍚",
        bookmark: "🔖",
        pricetag: "",
        icecream: "🍨",
        keywords: "",
        bbqapron: "",
        trashcan: "",
        cocktail: "🍸",
        dropdown: "▾",
        insecure: "🔓",
        unlocked: "🔓",
        oliveoil: "",
        hotsauce: "",
        leftward: "",
        sriracha: "",
        eggtimer: "",
        colander: "",
        nextpage: "⎘",
        "zoom out": "",
        barbecue: "",
        utensils: "🍴",
        display: "💻",
        refresh: "↻",
        tornado: "",
        rainbow: "🌈",
        "package": "📦",
        airplay: "",
        desktop: "💻",
        printer: "⎙",
        percent: "%",
        bonfire: "",
        savings: "",
        bicycle: "🚲",
        receipt: "",
        notepad: "",
        present: "🎁",
        speaker: "🔈",
        luggage: "",
        addcart: "",
        upright: "⬈",
        columns: "",
        adduser: "",
        droplet: "💧",
        avatars: "👥",
        weather: "",
        balloon: "🎈",
        dictate: "🎤",
        forward: "➡",
        retweet: "",
        comment: "💬",
        highway: "",
        fivedie: "⚄",
        adddate: "",
        arrival: "",
        warning: "⚠",
        "up left": "⬉",
        caution: "⛔",
        headset: "",
        "log out": "",
        endcall: "",
        feather: "",
        windows: "",
        signout: "",
        bowling: "",
        tractor: "🚜",
        "sign in": "",
        sausage: "",
        scaleup: "",
        dislike: "👎",
        loading: "",
        approve: "👍",
        shuffle: "🔀",
        battery: "🔋",
        noodles: "🍜",
        caravan: "🚐",
        handbag: "👜",
        fourdie: "⚃",
        pushpin: "📌",
        keyword: "",
        fitness: "",
        descend: "▾",
        syncing: "",
        checked: "✓",
        platter: "",
        "two die": "⚁",
        compass: "",
        "one die": "⚀",
        "private": "🔒",
        ereader: "",
        compose: "📝",
        chicken: "🐦",
        address: "",
        addfile: "",
        lodging: "🏨",
        picture: "🌄",
        visible: "👀",
        monitor: "💻",
        syringe: "💉",
        fragile: "",
        skylift: "🚡",
        zoomout: "",
        "zoom in": "",
        bandage: "",
        puzzle: "",
        reload: "",
        camera: "📷",
        locked: "🔒",
        zoomin: "",
        wrench: "🔧",
        basket: "",
        layout: "",
        action: "",
        images: "🌄",
        secure: "🔒",
        hockey: "",
        expand: "⤢",
        photos: "🌄",
        sample: "",
        avatar: "👤",
        unlock: "🔓",
        videos: "📹",
        notice: "",
        target: "◎",
        layers: "",
        tunnel: "",
        logout: "",
        knight: "♞",
        onedie: "⚀",
        locate: "",
        twodie: "⚁",
        "log in": "",
        camper: "🚐",
        signin: "",
        ascend: "▴",
        weight: "",
        resume: "",
        charts: "",
        record: "●",
        burger: "🍔",
        rewind: "⏪",
        pencil: "✎",
        hyphen: "-",
        hanger: "",
        shrimp: "🍤",
        turkey: "",
        laptop: "",
        remove: "-",
        sixdie: "⚅",
        tablet: "",
        tennis: "🎾",
        "public": "🔓",
        carrot: "",
        "delete": "␡",
        iphone: "",
        rocket: "🚀",
        coffee: "☕",
        folder: "📁",
        bottle: "",
        outlet: "",
        mobile: "",
        fishes: "",
        eraser: "✐",
        teapot: "",
        volume: "🔈",
        upleft: "⬉",
        tagged: "",
        upload: "",
        pepper: "",
        office: "🏢",
        shower: "🚿",
        repeat: "🔁",
        replay: "↺",
        search: "🔎",
        attach: "📎",
        soccer: "⚽",
        street: "",
        scales: "⚖",
        outbox: "📤",
        stereo: "",
        cursor: "",
        boxing: "",
        garage: "",
        ribbon: "🎀",
        knife: "🔪",
        share: "",
        write: "✎",
        stove: "",
        erase: "✐",
        scale: "",
        trash: "",
        heart: "♥",
        zelda: "",
        apron: "",
        medal: "",
        quill: "",
        phone: "📞",
        reply: "↩",
        purse: "👜",
        steak: "",
        email: "✉",
        inbox: "📥",
        right: "➡",
        pizza: "🍕",
        users: "👥",
        alarm: "⏰",
        timer: "⏱",
        cloud: "☁",
        apple: "🍏",
        watch: "⌚",
        store: "🏬",
        sunny: "☀",
        coins: "",
        clock: "⏲",
        flash: "⌁",
        stock: "",
        crate: "",
        rainy: "☔",
        earth: "🌎",
        world: "🌎",
        globe: "🌐",
        music: "♫",
        audio: "♫",
        sound: "🔈",
        grass: "",
        radio: "📻",
        image: "🌄",
        photo: "🌄",
        video: "📹",
        pause: "",
        eject: "⏏",
        close: "␡",
        hiker: "",
        index: "",
        check: "✓",
        train: "🚆",
        minus: "-",
        books: "📚",
        ebook: "",
        truck: "🚚",
        flame: "",
        enter: "",
        login: "",
        sweep: "",
        plane: "✈",
        alert: "⚠",
        broom: "",
        chess: "♞",
        visit: "",
        merge: "",
        nodes: "",
        quote: "“",
        print: "⎙",
        knob: "",
        boat: "🚢",
        font: "",
        text: "",
        list: "",
        zoom: "",
        view: "👀",
        look: "👀",
        link: "🔗",
        move: "",
        fuel: "⛽",
        edit: "✎",
        cook: "🍳",
        oven: "",
        file: "📄",
        bike: "🚲",
        wifi: "",
        sync: "",
        road: "",
        redo: "↻",
        draw: "✏",
        fork: "",
        help: "❓",
        info: "ℹ",
        exit: "",
        golf: "",
        fire: "🔥",
        plus: "+",
        lock: "🔒",
        idea: "💡",
        coal: "",
        tags: "",
        ipad: "",
        rows: "",
        news: "📰",
        flag: "⚑",
        book: "📕",
        page: "",
        like: "👍",
        undo: "↺",
        taxi: "🚖",
        hike: "",
        pool: "",
        salt: "",
        skip: "⏭",
        stop: "■",
        bird: "🐦",
        play: "▶",
        plug: "🔌",
        tree: "🌳",
        leaf: "🍂",
        yoga: "",
        disc: "💿",
        love: "♥",
        star: "⋆",
        beer: "🍺",
        wind: "",
        crop: "",
        next: "▻",
        save: "💾",
        chef: "",
        call: "📞",
        corn: "",
        gear: "⚙",
        dial: "",
        send: "",
        mail: "✉",
        home: "⌂",
        pill: "💊",
        hook: "",
        rain: "☔",
        back: "⬅",
        form: "",
        bell: "🔔",
        left: "⬅",
        bank: "🏦",
        work: "💼",
        time: "⏲",
        cash: "💵",
        fish: "🐟",
        safe: "",
        down: "⬇",
        drop: "💧",
        gift: "🎁",
        chat: "💬",
        cart: "",
        date: "📅",
        talk: "💬",
        user: "👤",
        cell: "📱",
        car: "🚘",
        sun: "☀",
        atm: "🏧",
        tip: "",
        dna: "",
        box: "📦",
        bed: "🏨",
        fax: "📠",
        map: "",
        rss: "",
        gps: "",
        pin: "📍",
        hdd: "",
        mug: "☕",
        pen: "✒",
        fog: "",
        mic: "🎤",
        cog: "⚙",
        tea: "🍵",
        fan: "",
        png: "",
        cab: "🚖",
        add: "+",
        bbq: "",
        tag: "",
        "new": "🆕",
        bus: "🚍",
        ban: "🚫",
        key: "🔑",
        cfl: "",
        out: "",
        exe: "",
        zip: "",
        gas: "⛽",
        doc: "",
        ppt: "",
        pdf: "",
        eye: "👀",
        jpg: "",
        up: "⬆",
        za: "🍕"
    };
}

SSPika.prototype.getCharcode = function(options) {
    return this.charcode[options];
};

module.exports = SSPika;